- name: Restart mysql service
  action: service name=mysqld enabled=yes state=restarted
  
- name: Check if mysql root user has a password for localhost
  command: mysqladmin -uroot -p{{ icinga_root_mysql_pass }} status
  ignore_errors: True
  register: icinga_mysql_root_pass_exists

- name: Check if mysql root user has a password for fqdn
  command: mysqladmin -uroot -p{{ icinga_root_mysql_pass }} -h {{ ansible_fqdn }} status
  ignore_errors: True
  register: icinga_fqdn_mysql_root_pass_exists
  
# Set the root password for mysql.
- name: Set root password for mysql localhost
  command: mysqladmin -uroot password {{ icinga_root_mysql_pass }}
  when: icinga_mysql_root_pass_exists.rc
  
- name: Set root password for mysql for fqdn
  command: mysqladmin -uroot -h {{ ansible_fqdn }} password {{ icinga_root_mysql_pass }}
  when: icinga_fqdn_mysql_root_pass_exists.rc
 
- name: Create icinga database
  mysql_db: name=icinga2 
            state=present
            login_user=root
            login_password={{ icinga_root_mysql_pass }}
  
# Grant privileges icinga user.
- name: Set icinga user previliges
  mysql_user: name=icinga password={{ icinga_user_mysql_pass }} priv=icinga2.*:ALL state=present login_user=root login_password={{ icinga_root_mysql_pass }}

- name: Check if table icinga_dbversion in icinga database exists 
  command: mysql -N -s --user=root --password={{ icinga_root_mysql_pass }} --database icinga2 -e "select count(*) from information_schema.tables where table_schema='icinga2' and table_name like '%dbversion'"
  register: icinga_dbversion

- name: Import Icinga 2 IDO schema
  shell: mysql --user=root --password={{ icinga_root_mysql_pass }} icinga2 < {{ icinga2_ido_mysql_schema }}
  when: icinga_dbversion.stdout|int == 0
  
- name: Copy ido-mysql config file
  template: src=templates/etc/icinga2/features-available/ido-mysql.conf.j2
            dest=/etc/icinga2/features-available/ido-mysql.conf 
            owner=icinga group=icinga mode=0640

- name: Enable icinga2 features
  shell: icinga2 feature enable ido-mysql statusdata compatlog command
  notify: restart icinga2
  
